#!/bin/bash


python gru_onehot_time.py data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.seqs.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.times.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.labels results/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0_hidden_256.result_subset_1_iter1 570 1 256
python gru_onehot_time.py data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.seqs.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.times.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.labels results/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0_hidden_256.result_subset_1_iter2 570 1 256
python gru_onehot_time.py data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.seqs.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.times.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.labels results/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0_hidden_256.result_subset_1_iter3 570 1 256
python gru_onehot_time.py data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.seqs.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.times.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.labels results/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0_hidden_256.result_subset_1_iter4 570 1 256
python gru_onehot_time.py data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.seqs.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.times.ll.subset_1 data/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0.p.labels results/2_1_outpatient_De_V_Di_M_S_enc_cutoff_0_hidden_256.result_subset_1_iter5 570 1 256




