#!/bin/bash

python gru_onehot_time.py data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.seqs.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.times.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.labels results/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5_hidden_256.result_iter_1 534 1 256
python gru_onehot_time.py data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.seqs.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.times.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.labels results/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5_hidden_256.result_iter_2 534 1 256
python gru_onehot_time.py data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.seqs.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.times.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.labels results/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5_hidden_256.result_iter_3 534 1 256
python gru_onehot_time.py data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.seqs.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.times.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.labels results/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5_hidden_256.result_iter_4 534 1 256
python gru_onehot_time.py data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.seqs.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.times.ll data/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5.p.labels results/1_1_outpatient_De_V_Di_M_S_enc_cutoff_5_hidden_256.result_iter_5 534 1 256

